-- Backfill teams.short_name with Torvik-style short names ("Duke" instead of
-- "Duke Blue Devils"). Source of truth lives in data/team_short_names.json,
-- which the NatStat ingest also reads to keep this column populated on
-- subsequent re-ingest.
--
-- The mapping was derived from torvik_player_stats.team_name (the most-common
-- name per natstat_id), with manual overrides for two NatStat-only programs
-- (Hartford and Saint Francis NY) that no longer appear in Torvik data.

UPDATE teams t
SET short_name = m.short_name,
    updated_at = now()
FROM (VALUES
  ('ACU', 'Abilene Christian'),
  ('AFA', 'Air Force'),
  ('AKR', 'Akron'),
  ('ALA', 'Alabama'),
  ('ALAM', 'Alabama A&M'),
  ('ALB', 'Albany'),
  ('ALC', 'Alcorn St.'),
  ('ALST', 'Alabama St.'),
  ('AMER', 'American'),
  ('APP', 'Appalachian St.'),
  ('APSU', 'Austin Peay'),
  ('ARIZ', 'Arizona'),
  ('ARK', 'Arkansas'),
  ('ARMY', 'Army'),
  ('ARST', 'Arkansas St.'),
  ('ASU', 'Arizona St.'),
  ('AUB', 'Auburn'),
  ('BAY', 'Baylor'),
  ('BC', 'Boston College'),
  ('BELL', 'Bellarmine'),
  ('BELM', 'Belmont'),
  ('BETH', 'Bethune Cookman'),
  ('BGSU', 'Bowling Green'),
  ('BING', 'Binghamton'),
  ('BOIS', 'Boise St.'),
  ('BONA', 'St. Bonaventure'),
  ('BRAD', 'Bradley'),
  ('BRWN', 'Brown'),
  ('BRY', 'Bryant'),
  ('BSU', 'Ball St.'),
  ('BU', 'Boston University'),
  ('BUCK', 'Bucknell'),
  ('BUFF', 'Buffalo'),
  ('BUTL', 'Butler'),
  ('BYU', 'BYU'),
  ('CAL', 'California'),
  ('CAMP', 'Campbell'),
  ('CANI', 'Canisius'),
  ('CBU', 'Cal Baptist'),
  ('CCAR', 'Coastal Carolina'),
  ('CCSU', 'Central Connecticut'),
  ('CHAR', 'Charlotte'),
  ('CHAT', 'Chattanooga'),
  ('CHIS', 'Chicago St.'),
  ('CHSO', 'Charleston Southern'),
  ('CINC', 'Cincinnati'),
  ('CITA', 'The Citadel'),
  ('CLEM', 'Clemson'),
  ('CLST', 'Cleveland St.'),
  ('CMU', 'Central Michigan'),
  ('COFC', 'Charleston'),
  ('COLG', 'Colgate'),
  ('COLO', 'Colorado'),
  ('COLU', 'Columbia'),
  ('CONN', 'Connecticut'),
  ('COPP', 'Coppin St.'),
  ('CORN', 'Cornell'),
  ('COST', 'Colorado St.'),
  ('CREI', 'Creighton'),
  ('CSF', 'Cal St. Fullerton'),
  ('CSN', 'Cal St. Northridge'),
  ('CSUB', 'Cal St. Bakersfield'),
  ('CWM', 'William & Mary'),
  ('DART', 'Dartmouth'),
  ('DAV', 'Davidson'),
  ('DEL', 'Delaware'),
  ('DEN', 'Denver'),
  ('DEP', 'DePaul'),
  ('DEST', 'Delaware St.'),
  ('DET', 'Detroit Mercy'),
  ('DREX', 'Drexel'),
  ('DRKE', 'Drake'),
  ('DUKE', 'Duke'),
  ('DUQ', 'Duquesne'),
  ('ECU', 'East Carolina'),
  ('EIU', 'Eastern Illinois'),
  ('EKU', 'Eastern Kentucky'),
  ('ELON', 'Elon'),
  ('EMU', 'Eastern Michigan'),
  ('ETSU', 'East Tennessee St.'),
  ('EVAN', 'Evansville'),
  ('EWU', 'Eastern Washington'),
  ('FAIR', 'Fairfield'),
  ('FAMU', 'Florida A&M'),
  ('FAU', 'Florida Atlantic'),
  ('FDU', 'Fairleigh Dickinson'),
  ('FGCU', 'Florida Gulf Coast'),
  ('FIU', 'FIU'),
  ('FLA', 'Florida'),
  ('FORD', 'Fordham'),
  ('FRES', 'Fresno St.'),
  ('FSU', 'Florida St.'),
  ('FURM', 'Furman'),
  ('GASO', 'Georgia Southern'),
  ('GB', 'Green Bay'),
  ('GCU', 'Grand Canyon'),
  ('GMU', 'George Mason'),
  ('GONZ', 'Gonzaga'),
  ('GRAM', 'Grambling St.'),
  ('GSU', 'Georgia St.'),
  ('GT', 'Georgia Tech'),
  ('GU', 'Georgetown'),
  ('GWB', 'Gardner Webb'),
  ('GWU', 'George Washington'),
  ('HAMP', 'Hampton'),
  ('HART', 'Hartford'),
  ('HARV', 'Harvard'),
  ('HAW', 'Hawaii'),
  ('HC', 'Holy Cross'),
  ('HCU', 'Houston Christian'),
  ('HOFS', 'Hofstra'),
  ('HOU', 'Houston'),
  ('HOW', 'Howard'),
  ('HPU', 'High Point'),
  ('ID', 'Idaho'),
  ('IDST', 'Idaho St.'),
  ('ILL', 'Illinois'),
  ('ILST', 'Illinois St.'),
  ('INCW', 'Incarnate Word'),
  ('IND', 'Indiana'),
  ('INST', 'Indiana St.'),
  ('IONA', 'Iona'),
  ('IOWA', 'Iowa'),
  ('ISU', 'Iowa St.'),
  ('IUPUI', 'IU Indy'),
  ('JAX', 'Jacksonville'),
  ('JMU', 'James Madison'),
  ('JSU', 'Jackson St.'),
  ('JXST', 'Jacksonville St.'),
  ('KENN', 'Kennesaw St.'),
  ('KENT', 'Kent St.'),
  ('KSU', 'Kansas St.'),
  ('KU', 'Kansas'),
  ('LAF', 'Lafayette'),
  ('LAM', 'Lamar'),
  ('LAS', 'La Salle'),
  ('LBSU', 'Long Beach St.'),
  ('LEH', 'Lehigh'),
  ('LEMN', 'Le Moyne'),
  ('LIB', 'Liberty'),
  ('LIND', 'Lindenwood'),
  ('LIP', 'Lipscomb'),
  ('LIU', 'LIU'),
  ('LMD', 'Loyola MD'),
  ('LMU', 'Loyola Marymount'),
  ('LONG', 'Longwood'),
  ('LOYO', 'Loyola Chicago'),
  ('LSU', 'LSU'),
  ('LTU', 'Louisiana Tech'),
  ('MAN', 'Manhattan'),
  ('MAR', 'Marist'),
  ('MARQ', 'Marquette'),
  ('MASS', 'Massachusetts'),
  ('MCN', 'McNeese St.'),
  ('MCYH', 'Mercyhurst'),
  ('MEM', 'Memphis'),
  ('MERC', 'Mercer'),
  ('MERR', 'Merrimack'),
  ('MIA', 'Miami FL'),
  ('MICH', 'Michigan'),
  ('MILW', 'Milwaukee'),
  ('MINN', 'Minnesota'),
  ('MIO', 'Miami OH'),
  ('MISS', 'Mississippi'),
  ('MIZZ', 'Missouri'),
  ('MON', 'Monmouth'),
  ('MONT', 'Montana'),
  ('MORE', 'Morehead St.'),
  ('MORG', 'Morgan St.'),
  ('MOST', 'Missouri St.'),
  ('MRSH', 'Marshall'),
  ('MSM', 'Mount St. Mary''s'),
  ('MSST', 'Mississippi St.'),
  ('MSU', 'Michigan St.'),
  ('MTST', 'Montana St.'),
  ('MTSU', 'Middle Tennessee'),
  ('MURR', 'Murray St.'),
  ('MVSU', 'Mississippi Valley St.'),
  ('NAL', 'North Alabama'),
  ('NAU', 'Northern Arizona'),
  ('NAVY', 'Navy'),
  ('NCAT', 'North Carolina A&T'),
  ('NCC', 'North Carolina Central'),
  ('NCSU', 'N.C. State'),
  ('ND', 'Notre Dame'),
  ('NDSU', 'North Dakota St.'),
  ('NEB', 'Nebraska'),
  ('NEBO', 'Nebraska Omaha'),
  ('NEV', 'Nevada'),
  ('NHV', 'New Haven'),
  ('NIAG', 'Niagara'),
  ('NICH', 'Nicholls St.'),
  ('NIU', 'Northern Illinois'),
  ('NJIT', 'NJIT'),
  ('NKU', 'Northern Kentucky'),
  ('NM', 'New Mexico'),
  ('NMSU', 'New Mexico St.'),
  ('NOCO', 'Northern Colorado'),
  ('NORF', 'Norfolk St.'),
  ('NOVA', 'Villanova'),
  ('NU', 'Northeastern'),
  ('NW', 'Northwestern'),
  ('NWSU', 'Northwestern St.'),
  ('OAK', 'Oakland'),
  ('ODU', 'Old Dominion'),
  ('OHIO', 'Ohio'),
  ('OKSU', 'Oklahoma St.'),
  ('ORE', 'Oregon'),
  ('ORST', 'Oregon St.'),
  ('ORU', 'Oral Roberts'),
  ('OSU', 'Ohio St.'),
  ('OU', 'Oklahoma'),
  ('PAC', 'Pacific'),
  ('PENN', 'Penn'),
  ('PEPP', 'Pepperdine'),
  ('PFW', 'Purdue Fort Wayne'),
  ('PITT', 'Pittsburgh'),
  ('POLY', 'Cal Poly'),
  ('PORT', 'Portland'),
  ('POST', 'Portland St.'),
  ('PRES', 'Presbyterian'),
  ('PRIN', 'Princeton'),
  ('PROV', 'Providence'),
  ('PSU', 'Penn St.'),
  ('PUR', 'Purdue'),
  ('PVAM', 'Prairie View A&M'),
  ('QUIN', 'Quinnipiac'),
  ('QUNC', 'Queens'),
  ('RAD', 'Radford'),
  ('RICE', 'Rice'),
  ('RICH', 'Richmond'),
  ('RID', 'Rider'),
  ('RMU', 'Robert Morris'),
  ('RUTG', 'Rutgers'),
  ('SAC', 'Sacramento St.'),
  ('SAMF', 'Samford'),
  ('SAMH', 'Sam Houston St.'),
  ('SBRK', 'Stony Brook'),
  ('SC', 'South Carolina'),
  ('SCL', 'Santa Clara'),
  ('SCST', 'South Carolina St.'),
  ('SCU', 'USC Upstate'),
  ('SDAK', 'South Dakota'),
  ('SDST', 'South Dakota St.'),
  ('SDSU', 'San Diego St.'),
  ('SEA', 'Seattle'),
  ('SELU', 'Southeastern Louisiana'),
  ('SEMO', 'Southeast Missouri St.'),
  ('SETON', 'Seton Hall'),
  ('SF', 'San Francisco'),
  ('SFA', 'Stephen F. Austin'),
  ('SFNY', 'St. Francis NY'),
  ('SFPA', 'Saint Francis'),
  ('SHU', 'Sacred Heart'),
  ('SIE', 'Siena'),
  ('SIND', 'Southern Indiana'),
  ('SIU', 'Southern Illinois'),
  ('SIUE', 'SIU Edwardsville'),
  ('SJST', 'San Jose St.'),
  ('SLU', 'Saint Louis'),
  ('SMC', 'Saint Mary''s'),
  ('SMU', 'SMU'),
  ('SOMS', 'Southern Miss'),
  ('SOU', 'Southern'),
  ('SPC', 'Saint Peter''s'),
  ('STAN', 'Stanford'),
  ('STET', 'Stetson'),
  ('STJN', 'St. John''s'),
  ('STJS', 'Saint Joseph''s'),
  ('STMN', 'St. Thomas'),
  ('STNH', 'Stonehill'),
  ('SUU', 'Southern Utah'),
  ('SYR', 'Syracuse'),
  ('TAMC', 'Texas A&M Corpus Christi'),
  ('TAMU', 'Texas A&M'),
  ('TARL', 'Tarleton St.'),
  ('TCU', 'TCU'),
  ('TEMP', 'Temple'),
  ('TENN', 'Tennessee'),
  ('TEX', 'Texas'),
  ('TMCM', 'East Texas A&M'),
  ('TOL', 'Toledo'),
  ('TOW', 'Towson'),
  ('TRGV', 'UT Rio Grande Valley'),
  ('TROY', 'Troy'),
  ('TSU', 'Tennessee St.'),
  ('TTU', 'Tennessee Tech'),
  ('TUL', 'Tulane'),
  ('TULS', 'Tulsa'),
  ('TXSO', 'Texas Southern'),
  ('TXST', 'Texas St.'),
  ('TXT', 'Texas Tech'),
  ('UAB', 'UAB'),
  ('UALR', 'Little Rock'),
  ('UAPB', 'Arkansas Pine Bluff'),
  ('UCA', 'Central Arkansas'),
  ('UCD', 'UC Davis'),
  ('UCF', 'UCF'),
  ('UCI', 'UC Irvine'),
  ('UCLA', 'UCLA'),
  ('UCR', 'UC Riverside'),
  ('UCSB', 'UC Santa Barbara'),
  ('UD', 'Dayton'),
  ('UGA', 'Georgia'),
  ('UIC', 'Illinois Chicago'),
  ('UK', 'Kentucky'),
  ('UL', 'Louisville'),
  ('ULL', 'Louisiana'),
  ('ULM', 'Louisiana Monroe'),
  ('UMBC', 'UMBC'),
  ('UMD', 'Maryland'),
  ('UME', 'Maine'),
  ('UMES', 'Maryland Eastern Shore'),
  ('UMKC', 'UMKC'),
  ('UML', 'UMass Lowell'),
  ('UNC', 'North Carolina'),
  ('UNCA', 'UNC Asheville'),
  ('UNCG', 'UNC Greensboro'),
  ('UNCW', 'UNC Wilmington'),
  ('UND', 'North Dakota'),
  ('UNF', 'North Florida'),
  ('UNH', 'New Hampshire'),
  ('UNI', 'Northern Iowa'),
  ('UNLV', 'UNLV'),
  ('UNO', 'New Orleans'),
  ('UNT', 'North Texas'),
  ('URI', 'Rhode Island'),
  ('USA', 'South Alabama'),
  ('USC', 'USC'),
  ('USCD', 'UC San Diego'),
  ('USD', 'San Diego'),
  ('USF', 'South Florida'),
  ('USU', 'Utah St.'),
  ('UTA', 'UT Arlington'),
  ('UTAH', 'Utah'),
  ('UTCH', 'Utah Tech'),
  ('UTEP', 'UTEP'),
  ('UTM', 'Tennessee Martin'),
  ('UTSA', 'UTSA'),
  ('UVA', 'Virginia'),
  ('UVM', 'Vermont'),
  ('UVU', 'Utah Valley'),
  ('VALP', 'Valparaiso'),
  ('VAND', 'Vanderbilt'),
  ('VCU', 'VCU'),
  ('VMI', 'VMI'),
  ('VT', 'Virginia Tech'),
  ('WAG', 'Wagner'),
  ('WASH', 'Washington'),
  ('WCAR', 'Western Carolina'),
  ('WEB', 'Weber St.'),
  ('WF', 'Wake Forest'),
  ('WGEO', 'West Georgia'),
  ('WICH', 'Wichita St.'),
  ('WINT', 'Winthrop'),
  ('WISC', 'Wisconsin'),
  ('WIU', 'Western Illinois'),
  ('WKU', 'Western Kentucky'),
  ('WMU', 'Western Michigan'),
  ('WOFF', 'Wofford'),
  ('WRIG', 'Wright St.'),
  ('WSU', 'Washington St.'),
  ('WV', 'West Virginia'),
  ('WYO', 'Wyoming'),
  ('XU', 'Xavier'),
  ('YALE', 'Yale'),
  ('YSU', 'Youngstown St.')

) AS m(natstat_id, short_name)
WHERE t.natstat_id = m.natstat_id;
